### ISSUE TITLE
A few improvement ideas

### ISSUE THREAD

**Issue by 1ue999** [BnDLett/NameValidation#1]
-Kick message should provide a little bit more context (i kinda doubt that most players know how to read regex patterns)
-There should be a unique kick message for having an empty name, since it is not included in the pattern
-Why so many classes?

**Comment by BnDLett** [comment]
It's a personal style choice. It makes no real difference to the actual functionality. Additionally, I see it as general good practice as others will be able to build on top of the code (if they want to).
